@echo off
echo Initializing Git Repository...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit - Case Study"
echo Setting main branch...
git branch -M main
echo Linking to GitHub...
git remote add origin https://github.com/maheshahir6118/inrisk_weather_tak.git
echo Pushing to GitHub (this may ask you to login)...
git push -u origin main
echo DONE! Press any key to exit.
pause
